Diplom_WebSite_Taras/Controllers/AdminUserRoleController.cs
using Diplom_WebSite_Taras.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Diplom_WebSite_Taras.ApplicationSignInManager;
using PagedList;
using System.Net;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;

namespace Diplom_WebSite_Taras.Controllers
{
    public class AdminUserRoleController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;

        // Controllers

        // GET: /Admin/
        [Authorize(Roles = "Administrator")]
        #region public ActionResult Index(string searchStringUserNameOrEmail)
        public ActionResult Index(string searchStringUserNameOrEmail, string currentFilter, int? page)
        {
            try
            {
                int intPage = 1;
                int intPageSize = 5;
                int intTotalPageCount = 0;

                if (searchStringUserNameOrEmail != null)
                {
                    intPage = 1;
                }
                else
                {
                    if (currentFilter != null)
                    {
                        searchStringUserNameOrEmail = currentFilter;
                        intPage = page ?? 1;
                    }
                    else
                    {
                        searchStringUserNameOrEmail = "";
                        intPage = page ?? 1;
                    }
                }

                ViewBag.CurrentFilter = searchStringUserNameOrEmail;

                List<ExpandedUserDTO> col_UserDTO = new List<ExpandedUserDTO>();
                int intSkip = (intPage - 1) * intPageSize;

                intTotalPageCount = UserManager.Users
                    .Where(x => x.UserName.Contains(searchStringUserNameOrEmail))
                    .Count();

                var result = UserManager.Users
                    .Where(x => x.UserName.Contains(searchStringUserNameOrEmail))
                    .OrderBy(x => x.UserName)
                    .Skip(intSkip)
                    .Take(intPageSize)
                    .ToList();

                foreach (var item in result)
                {
                    ExpandedUserDTO objUserDTO = new ExpandedUserDTO();

                    objUserDTO.UserName = item.UserName;
                    objUserDTO.Email = item.Email;
                    objUserDTO.LockoutEndDateUtc = item.LockoutEndDateUtc;

                    col_UserDTO.Add(objUserDTO);
                }

                // Set the number of pages
                var _UserDTOAsIPagedList =
                    new StaticPagedList<ExpandedUserDTO>
                    (
                        col_UserDTO, intPage, intPageSize, intTotalPageCount
                        );

                return View(_UserDTOAsIPagedList);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Помилка: " + ex);
                List<ExpandedUserDTO> col_UserDTO = new List<ExpandedUserDTO>();

                return View(col_UserDTO.ToPagedList(1, 25));
            }
        }
        #endregion

        // Users *****************************

        // GET: /Admin/Edit/Create 
        [Authorize(Roles = "Administrator")]
        #region public ActionResult Create()
        public ActionResult Create()
        {
            ExpandedUserDTO objExpandedUserDTO = new ExpandedUserDTO();

            ViewBag.Roles = GetAllRolesAsSelectList();

            return View(objExpandedUserDTO);
        }
        #endregion

        // PUT: /Admin/Create
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        #region public ActionResult Create(ExpandedUserDTO paramExpandedUserDTO)
        public ActionResult Create(ExpandedUserDTO paramExpandedUserDTO)
        {
            try
            {
                if (paramExpandedUserDTO == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var Email = paramExpandedUserDTO.Email.Trim();
                var UserName = paramExpandedUserDTO.Email.Trim();
                var Password = paramExpandedUserDTO.Password.Trim();

                if (Email == "")
                {
                    throw new Exception("Немає електронної пошти користувача (Email).");
                }

                if (Password == "")
                {
                    throw new Exception("Немає пароля.");
                }

                // UserName is LowerCase of the Email
                UserName = Email.ToLower();

                // Create user

                var objNewAdminUser = new ApplicationUser { UserName = UserName, Email = Email };
                var AdminUserCreateResult = UserManager.Create(objNewAdminUser, Password);

                if (AdminUserCreateResult.Succeeded == true)
                {
                    string strNewRole = Convert.ToString(Request.Form["Roles"]);

                    if (strNewRole != "0")
                    {
                        // Put user in role
                        UserManager.AddToRole(objNewAdminUser.Id, strNewRole);
                    }

                    return Redirect("~/AdminUserRole");
                }
                else
                {
                    ViewBag.Roles = GetAllRolesAsSelectList();
                    ModelState.AddModelError(string.Empty,
                        "Помилка: Неможливо створити користувача. Перевірте налаштування пароля.");
                    return View(paramExpandedUserDTO);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Roles = GetAllRolesAsSelectList();
                ModelState.AddModelError(string.Empty, "Помилка: " + ex);
                return View("Create");
            }
        }
        #endregion

        // GET: /Admin/Edit/TestUser 
        [Authorize(Roles = "Administrator")]
        #region public ActionResult EditUser(string UserName)
        public ActionResult EditUser(string UserName)
        {
            if (UserName == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpandedUserDTO objExpandedUserDTO = GetUser(UserName);
            if (objExpandedUserDTO == null)
            {
                return HttpNotFound();
            }
            return View(objExpandedUserDTO);
        }
        #endregion

        // PUT: /Admin/EditUser
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        #region public ActionResult EditUser(ExpandedUserDTO paramExpandedUserDTO)
        public ActionResult EditUser(ExpandedUserDTO paramExpandedUserDTO)
        {
            try
            {
                if (paramExpandedUserDTO == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                ExpandedUserDTO objExpandedUserDTO = UpdateDTOUser(paramExpandedUserDTO);

                if (objExpandedUserDTO == null)
                {
                    return HttpNotFound();
                }

                return Redirect("~/AdminUserRole");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Помилка: " + ex);
                return View("EditUser", GetUser(paramExpandedUserDTO.UserName));
            }
        }
        #endregion

        // DELETE: /Admin/DeleteUser
        [Authorize(Roles = "Administrator")]
        #region public ActionResult DeleteUser(string UserName)
        public ActionResult DeleteUser(string UserName)
        {
            try
            {
                if (UserName == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                if (UserName.ToLower() == this.User.Identity.Name.ToLower())
                {
                    ModelState.AddModelError(
                        string.Empty, "Помилка: Неможливо видалити даного користувача.");

                    return View("EditUser");
                }

                ExpandedUserDTO objExpandedUserDTO = GetUser(UserName);

                if (objExpandedUserDTO == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    DeleteUser(objExpandedUserDTO);
                }

                return Redirect("~/AdminUserRole");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Помилка: " + ex);
                return View("EditUser", GetUser(UserName));
            }
        }
        #endregion

        // GET: /Admin/EditRoles/TestUser 
        [Authorize(Roles = "Administrator")]
        #region ActionResult EditRoles(string UserName)
        public ActionResult EditRoles(string UserName)
        {
            if (UserName == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            UserName = UserName.ToLower();

            // Check that we have an actual user
            ExpandedUserDTO objExpandedUserDTO = GetUser(UserName);

            if (objExpandedUserDTO == null)
            {
                return HttpNotFound();
            }

            UserAndRolesDTO objUserAndRolesDTO =
                GetUserAndRoles(UserName);

            return View(objUserAndRolesDTO);
        }
        #endregion

        // PUT: /Admin/EditRoles/TestUser 
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        #region public ActionResult EditRoles(UserAndRolesDTO paramUserAndRolesDTO)

Diplom_WebSite_Taras/Views/AdminUserRole/AddRole.cshtml
@model Diplom_WebSite_Taras.Models.RoleDTO

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Створити нову роль</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RoleName,
           htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoleName,
               new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoleName,
               "",
               new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зберегти" class="btn btn-success" />
                @Html.ActionLink("Повернутися",
               "ViewAllRoles",
               null,
               new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

Diplom_WebSite_Taras/Views/AdminUserRole/Create.cshtml
@model Diplom_WebSite_Taras.Models.ExpandedUserDTO

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Створити нового користувача</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Email,
           htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email,
               new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "",
               new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password,
           htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password,
               new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password,
               "",
               new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Roles,
           htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Roles")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зберегти" class="btn btn-success" />
                @Html.ActionLink("Повернутися",
               "Index",
               null,
               new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

Diplom_WebSite_Taras/Views/AdminUserRole/EditRoles.cshtml
@model Diplom_WebSite_Taras.Models.UserAndRolesDTO

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <br />
    @Html.ValidationSummary(true,
    "",
    new { @class = "text-danger" })
    <div>
        @Html.ActionLink("Повернутися",
       "EditUser",
       new { UserName = Model.UserName },
       new { @class = "btn btn-default" })
        <input type="submit" value="Додати роль" class="btn btn-success" />
        @Html.DropDownList("AddRole")
    </div>
    <br />

    <table class="table">
        <tr>
            <th>
                Існуючі ролі:
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.colUserRoleDTO)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RoleName)
                </td>
                <td>
                    @if (!((Model.UserName.ToLower() ==
                        this.User.Identity.Name.ToLower()) &&
                        item.RoleName == "Administrator") &&
                        item.RoleName != "No Roles Found")
                    {
                        @Html.ActionLink("Видалити", "DeleteRole",
                       new { UserName = item.UserName, RoleName = item.RoleName },
                        new
                        {
                            onclick =
                        "return confirm('Чи ви дійсно бажаєте видалити цю роль?');"
                        })
                    }
                </td>
            </tr>
        }
    </table>
}

Diplom_WebSite_Taras/Views/AdminUserRole/EditUser.cshtml
@model Diplom_WebSite_Taras.Models.ExpandedUserDTO

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Змінити користувача</h4>
        @Html.ValidationSummary(true,
       "",
       new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName,
           htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.UserName,
               new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "",
               new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email,
           htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email,
               new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email,
               "",
               new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password,
           htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password,
               new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password,
               "",
               new { @class = "text-danger" })
            </div>
        </div>           

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зберегти" class="btn btn-default" />
                @Html.ActionLink("Назначити роль", "EditRoles",
               new { UserName = Model.UserName },
               new { @class = "btn btn-success" })
                @Html.ActionLink("Повернутися",
               "Index",
               null,
               new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

Diplom_WebSite_Taras/Views/AdminUserRole/Index.cshtml
@model PagedList.IPagedList<Diplom_WebSite_Taras.Models.ExpandedUserDTO>
@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<p>
    @Html.ActionLink("Створити нового користувача", "Create", null, new { @class = "btn btn-success" })
    @Html.ActionLink("Керування ролями", "ViewAllRoles", null, new { @class = "btn btn-success" })
    @Html.ActionLink("Повернутися", "../", "Home", null, new { @class = "btn btn-success" })
</p>
<br />
@using (Html.BeginForm("Index", "AdminUserRole", FormMethod.Get))
{

    <div class="form-group">
        Пошук:&nbsp; @Html.TextBox("searchStringUserNameOrEmail", ViewBag.CurrentFilter as string)

        <input type="submit" value="Знайти" />
    </div>
}
<br />

<table class="table">
    <tr>
        <th>
            Email, або ім'я
        </th>       
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Змінити", "EditUser", new { UserName = item.UserName }, new { @class = "btn btn-success btn-large" }) |
                @if ((item.UserName.ToLower() != this.User.Identity.Name.ToLower()))
                {
                    @Html.ActionLink("Видалити", "DeleteUser", new { UserName = item.UserName },
                    new { onclick = "return confirm('Чи Ви дійсно бажаєте видалити даного користувача?');" })
                }
            </td>
        </tr>
    }


</table>
<br />
<div class="text-center">
    Сторінка @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) із @Model.PageCount

    @Html.PagedListPager(Model,
    page => Url.Action("Index",
    new
    {
        page,
        searchStringUserNameOrEmail = ViewBag.searchStringUserNameOrEmail,
        currentFilter = ViewBag.CurrentFilter
    }))
    <hr />
    </div>

Diplom_WebSite_Taras/Views/AdminUserRole/ViewAllRoles.cshtml
@model IEnumerable<Diplom_WebSite_Taras.Models.RoleDTO>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<p>
    @Html.ActionLink("Повернутися", "Index", null, new { @class = "btn btn-success" })
    @Html.ActionLink("Додати роль", "AddRole", null, new { @class = "btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            Роль
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RoleName)
            </td>
            <td>
                @if (item.RoleName.ToLower() != "administrator")
                {
                    @Html.ActionLink("Видалити", "DeleteUserRole",
                   new { RoleName = item.RoleName },
                   new
                   {
                       onclick =
                   "return confirm('Чи Ви дійсно бажаєте видалити дану роль?');"
                   })
                }
            </td>

        </tr>
    }
</table>